{
  pkgs,
  inputs,
  username,
  dirName,
  ...
}:
{
  imports = [
    inputs.home-manager.nixosModules.home-manager
    ./packages.nix
    ../../modules/web/caddy.nix
  ];

  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    extraSpecialArgs = { inherit inputs username; };
    backupFileExtension = "backup";
  };

  nix.settings = {
    experimental-features = [
      "nix-command"
      "flakes"
    ];
    substituters = [ "https://cache.nixos.org" ];
    trusted-public-keys = [ "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" ];
    trusted-users = [
      "root"
      username
    ];
  };

  programs.zsh.enable = true;

  zramSwap.enable = false; # match nixos-infect
  /*
    zramSwap = {
      enable = true;
      priority = 100;
      algorithm = "lz4";
      memoryPercent = 50;
    };
  */

  fonts.packages = with pkgs; [
    nerd-fonts.fira-code
  ];

  environment.shellAliases = {
    h = "cd ~/${dirName}";
    hh = "cd ~/${dirName}/hosts/";
    hm = "cd ~/${dirName}/modules/";
    c = "clear";
    gs = "git status";
    gl = "git log --oneline --decorate --graph -5";
    ga = "git add";
    gaa = "git add -A";
    gc = "git commit";
    gp = "git push";
    llg = "lazygit";
    nclean = "nix-collect-garbage";
    gib = "xclip -sel c";
    nedit = "nvim ~/nixos/hosts/default/configuration.nix";
    hedit = "nvim ~/nixos/hosts/default/home.nix";
  };

  i18n.defaultLocale = "en_IE.UTF-8";

  users.users.${username} = {
    shell = pkgs.zsh;
    isNormalUser = true;
    extraGroups = [
      "wheel"
    ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBqQ5oSVdm2VwrRatrKCjT7jMqXQRWKk9yT2Bu1RBjHk askosia@laptop"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICHRzbBl2yBT8WZC9UyPkbe5WbBdq0ByQI8EERjc10Iu askosia@desktop"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFaLKzlmNCZd+fBvbXdro1QmGAK5L6GlvTlX0fxBGT9D askosia@windows"
    ];
  };

  services.openssh = {
    enable = true;
    ports = [ 22 ];
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "yes";
      AllowUsers = [
        "root"
        username
      ];
    };
  };

  # Everything below was autogenerated by nixos-infect

  # Workaround for https://github.com/NixOS/nix/issues/8502
  services.logrotate.checkConfig = false;

  boot.tmp.cleanOnBoot = true;
  networking.domain = "subnet11261649.vcn11261649.oraclevcn.com";

  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBqQ5oSVdm2VwrRatrKCjT7jMqXQRWKk9yT2Bu1RBjHk askosia@laptop"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICHRzbBl2yBT8WZC9UyPkbe5WbBdq0ByQI8EERjc10Iu askosia@desktop"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFaLKzlmNCZd+fBvbXdro1QmGAK5L6GlvTlX0fxBGT9D askosia@windows"
  ];

  system.stateVersion = "23.11";
}
